rules:
    default:
        protection:
          required_status_checks:
            contexts:
              - continuous-integration/travis-ci
              - codecov/project
              - Detekt
              - danger/danger
          required_pull_request_reviews: null
