version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha

    working_directory: ~/social-app

    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "presentation/build.gradle" }}

      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true

      - run:
          name: run iamnative
          command: ./iamnative.kexe

      - run:
          name: run iamnative
          command: chmod +x ./iamnative.kexe

      - run:
          name: run iamnative
          command: chmod u+x ./iamnative.kexe

      - run:
          name: install kotlin native
          command: bash install_kotlin_native.sh

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}