version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha

    working_directory: ~/my-app

    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true

      - run:
          name: Write Google Services JSON file
          command: echo "$google_services_json" > presentation/google-services.json

      - run:
          name: Run Tests
          command: ./gradlew test --stacktrace

      - run:
          name: Run JaCoCo
          command: ./gradlew build jacocoFullReport "-Pargs=ci,${CIRCLE_BUILD_NUM}"

      - run:
          name: Install bundle
          command: bundle install

      - run:
          name: Run Danger
          command: bundle exec danger

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}