version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha

    working_directory: ~/my-app

    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true

      - run:
          name: bundle_install
          command: bundle install

      - run:
          name: Add google-services.json
          command: echo "$google_services_json" > presentation/google-services.json

      - run:
          name: Run_jacocoFullReport
          command: ./gradlew build jacocoFullReport "-Pargs=ci,${CIRCLE_BUILD_NUM}"

      - run:
          name: Run_danger
          command: bundle exec danger

      - run:
          name: Upload jacoco report
          command: bash .upload_jacoco_files.sh

      - run:
          name: run anas1
          command: ./anas.kexe

      - run:
          name: run anas2
          command: chmod +x ./anas.kexe

      - run:
          name: run anas3
          command: chmod u+x ./anas.kexe

      - run:
          name: run ls
          command: ls

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}